# 🔹 Основные настройки Netlify
[build]
  publish = "public"  # Укажи папку, где лежат HTML-файлы
  command = ""        # Убираем команду сборки, т.к. нет Webpack/Vite

# 🔹 Кэширование статических файлов (CSS, JS, изображения)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"

# 🔹 Оптимизация кеша для HTML (чтобы обновления работали)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=600, must-revalidate"

# 🔹 Включаем Brotli + Gzip сжатие
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br, gzip"

# 🔹 Предзагрузка шрифтов (замени URL шрифтов на свои)
[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    Link = "</fonts/your-font.woff2>; rel=preload; as=font; type=font/woff2; crossorigin=anonymous"

# 🔹 Включаем Netlify Edge Functions для быстрой раздачи контента
[[edge_functions]]
  path = "/*"
  function = "server"

# 🔹 Защита сайта (CSP + HTTPS + XSS защита)
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'"

# 🔹 Оптимизация изображений (ленивая загрузка)
[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

# 🔹 Убираем FOUC (Flash of Unstyled Content) для CSS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 🔹 Редирректы

[[redirects]]
  from = "/en"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/ru"
  to = "/index-ru.html"
  status = 200
  force = true