# 🔹 Основные настройки Netlify
[build]
  publish = "/"  # Папка с HTML-файлами
  command = ""   # Нет Webpack/Vite, сборка не нужна

# 🔹 Кэширование статических файлов (CSS, JS, изображения)
[[headers]]
  for = "/*"
  [headers.values]
    Accept-Encoding = "gzip, br" # Автоматическое сжатие

# 🔹 Оптимизация кеша для HTML (уменьшили кеширование)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# 🔹 Предзагрузка шрифтов
[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    Link = "</fonts/your-font.woff2>; rel=preload; as=font; type=font/woff2; crossorigin=anonymous"

# 🔹 Защита сайта (CSP + HTTPS + XSS защита)
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'"

# 🔹 Оптимизация изображений (ленивая загрузка)
[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

# 🔹 Оптимизация CSS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 🔹 Редиректы (учитываем www и https)
[[redirects]]
  from = "https://www.topfhelm.com/en"
  to = "https://topfhelm.com/index.html"
  status = 301
  force = true

[[redirects]]
  from = "https://www.topfhelm.com/ru"
  to = "https://topfhelm.com/index-ru.html"
  status = 301
  force = true