# 🔹 Основные настройки Netlify
[build]
  publish = "/"  # Папка с HTML-файлами
  command = ""   # Нет Webpack/Vite, сборка не нужна

# 🔹 Кэширование статических файлов (CSS, JS, изображения)
[[headers]]
  for = "/*"
  [headers.values]
    Accept-Encoding = "gzip, br" # Автоматическое сжатие

# 🔹 Улучшенная поддержка Brotli и Gzip
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br, gzip"

# 🔹 Оптимизация кеша для HTML (уменьшили кеширование)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# 🔹 Предзагрузка шрифтов
[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    Link = "</fonts/your-font.woff2>; rel=preload; as=font; type=font/woff2; crossorigin=anonymous"

# 🔹 Защита сайта (CSP + HTTPS + XSS защита)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://code.jquery.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://img.youtube.com; connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com;"

# 🔹 Оптимизация изображений (ленивая загрузка)
[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

# 🔹 Оптимизация CSS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 🔹 Оптимизация кеширования JS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 🔹 Редиректы (учитываем www и https)
[[redirects]]
  from = "/en"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/ru"
  to = "/index-ru.html"
  status = 200
  force = true

[[redirects]]
  from = "https://www.topfhelm.com/en"
  to = "https://topfhelm.com/en"
  status = 301
  force = true

[[redirects]]
  from = "https://www.topfhelm.com/ru"
  to = "https://topfhelm.com/ru"
  status = 301
  force = true